### ISSUE TITLE
Problems with tqdm / pandas / swifter

### ISSUE THREAD

**Issue by g3n35i5** [mozilla/CorporaCreator#99]
The following exceptions occur when the code is executed:

```
Traceback (most recent call last):
  File "[hidden]/CorporaCreator/venv/lib/python3.6/site-packages/swifter-0.289-py3.6.egg/swifter/swifter.py", line 259, in apply
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "[hidden]/CorporaCreator/venv/lib/python3.6/site-packages/tqdm-4.32.2-py3.6.egg/tqdm/_tqdm.py", line 611, in pandas
    from pandas.core.groupby.groupby import DataFrameGroupBy, \
ImportError: cannot import name 'DataFrameGroupBy'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "[hidden]/CorporaCreator/venv/bin/create-corpora", line 11, in <module>
    load_entry_point('CorporaCreator==0.0.post0.dev159+g64d63b6.dirty', 'console_scripts', 'create-corpora')()
  File "[hidden]/CorporaCreator/venv/lib/python3.6/site-packages/CorporaCreator-0.0.post0.dev159+g64d63b6.dirty-py3.6.egg/corporacreator/tool.py", line 31, in run
    main(sys.argv[1:])
  File "[hidden]/CorporaCreator/venv/lib/python3.6/site-packages/CorporaCreator-0.0.post0.dev159+g64d63b6.dirty-py3.6.egg/corporacreator/tool.py", line 21, in main
    corpora.create()
  File "[hidden]/CorporaCreator/venv/lib/python3.6/site-packages/CorporaCreator-0.0.post0.dev159+g64d63b6.dirty-py3.6.egg/corporacreator/corpora.py", line 44, in create
    ].swifter.apply(func=lambda arg: self.common_wrapper(*arg), axis=1)
  File "[hidden]/CorporaCreator/venv/lib/python3.6/site-packages/swifter-0.289-py3.6.egg/swifter/swifter.py", line 288, in apply
  File "[hidden]/CorporaCreator/venv/lib/python3.6/site-packages/tqdm-4.32.2-py3.6.egg/tqdm/_tqdm.py", line 614, in pandas
    from pandas.core.groupby import DataFrameGroupBy, \
ImportError: cannot import name 'PanelGroupBy'
```

**Comment by g3n35i5** [comment]
Fixed by downgrading pandas to v0.24

**Comment by kdavis-mozilla** [comment]
I guess we should pin the pandas version?

**Comment by g3n35i5** [comment]
I think this is more a bug in tqdm than pandas but yes, it'd be a first step
